name = "rt-monitor-example-app"
working_directory = "./sandbox/rt-monitor-example-app/specification/"
[process]
    format = "regex"
    structure = "init;(filtering;conversion;display_chk)*"

[[process.tasks]]
    name = "init"
    [[process.tasks.pres]]
    [[process.tasks.posts]]
        name = "init_vars"
        format = "smt2"
        variables = "(main_realvalue_old:State Int)"
        formula = "(= main_realvalue_old 0)"        # inline formula.
    [[process.tasks.posts]]
        name = "init_fondo_display"
        file = "init_fondo_display.toml"       # local file.
    [[process.tasks.posts]]
        name = "init_time_bound"
        file = "./sandbox/rt-monitor-example-app/specification/init_time_bound.toml"       # relative path to file.

[[process.tasks]]
    name = "filtering"
    [[process.tasks.pres]]
        name = "filtering_pre"
        file = "/Users/clpombo/sandbox/invap-github/rt-monitor/sandbox/rt-monitor-example-app/specification/filtering_pre.toml"       # absolute path to file.
    [[process.tasks.posts]]
        name = "filtering_post"
        file = "filtering_post.toml"       # local file.
    [[process.tasks.posts]]
        name = "filtering_time_bound"
        file = "filtering_time_bound.toml"       # local file.
    [[process.tasks.checkpoints]]
        name = "filtering_chk"
        [[process.tasks.checkpoints.properties]]
            name = "12bitsreading"
            file = "12bitsreading.toml"       # local file.
        [[process.tasks.checkpoints.properties]]
            name = "additionbound"
            file = "additionbound.toml"       # local file.

[[process.tasks]]
    name = "conversion"
    [[process.tasks.pres]]
        name = "conversion_pre"
        file = "conversion_pre.toml"       # local file.
    [[process.tasks.posts]]
        name = "conversion_post"
        # For a PASS result in python format
        file = "conversion_post-py.toml"       # local file.
        # For a FAILED result in quantifier-free smt2 format due to z3.unknown
        # file = "conversion_post-smt2-qf.toml"       # local file.
        # For a FAILED result in smt2 format due to z3.unknown
        # file = "conversion_post-smt2-eq.toml"       # local file.
    [[process.tasks.checkpoints]]

[[process.checkpoints]]
    name = "display_chk"
    [[process.checkpoints.properties]]
        name = "barpointiscorrect"
        file = "barpointiscorrect.toml"       # local file.
    [[process.checkpoints.properties]]
        name = "bariscorrect"
        file = "bariscorrect.toml"       # local file.

[components]
    visual = true
    location = "./rt_monitor/framework/components/rt_monitor_example_app"
    [[components.list]]
        name = "adc"
        component_path = "./rt_monitor/framework/components/rt_monitor_example_app"
        component_file = "ex_adc_visual.py"
        component_name = "adc"
        visual_component_file = "ex_adcVisual.py"       # the visual component is assumed to be in the same location as the component
        visual_component_name = "adcVisual"
        visual = true
    [[components.list]]
        name = "display"
        component_file = "ex_display.py"
        component_name = "display"
        visual_component_file = "ex_displayVisual.py"
        visual_component_name = "displayVisual"
        visual = true
