format = "smt2"
variables = "(main_addition:State Int),(main_realvalue:State Int),(main_value_arr:State (Array Int Int))"
declarations = """(declare-fun sum ((Array Int Int) Int Int) Int)
                  (assert (forall ((a (Array Int Int)) (i Int)) (= (sum a i i) 0)))
                  (assert (forall ((a (Array Int Int)) (i Int) (j Int))
                              (=> (< i j)
                                  (= (sum a i j) (+ (select a i) (sum a (+ i 1) j)))
                              )
                          )
                  )"""
formula = """(and
    (forall ((i Int))
        (=>
            (and (<= 0 i) (< i 16))
            (and (<= 0 (select main_value_arr i)) (< (select main_value_arr i) 4096))
        )
    )
    (= main_addition (sum main_value_arr 0 16))
    (= main_realvalue (div main_addition 16))
)"""