name = "rt-monitor-example-app"
working_directory = "./path_to_files/"
[process]
    format = "graph"
[process.structure]
nodes = [
    ["init", "task"],
    ["to-loop", "operator:seq_composition"],
    ["control-loop-start", "operator:omega_start"],
    ["filtering", "task"],
    ["filtered-sample", "operator:seq_composition"],
    ["conversion", "task"],
    ["measurement", "operator:seq_composition"],
    ["display_chk", "checkpoint"],
    ["control-loop-end", "operator:omega_end"]
]
edges = [
    ["init","to-loop"],
    ["to-loop","control-loop-start"],
    ["control-loop-start","filtering"],
    ["filtering","filtered-sample"],
    ["filtered-sample","conversion"],
    ["conversion","measurement"],
    ["measurement","display_chk"],
    ["display_chk","control-loop-end"],
    ["control-loop-end", "control-loop-start"]
]
start = "init"


[[process.tasks]]
    name = "init"
    [[process.tasks.pres]]
    [[process.tasks.posts]]
        name = "init_vars"
        format = "protosmt2"
        variables = "(main_realvalue_old:State Int)"
        formula = "(= main_realvalue_old 0)"        # inline formula.
    [[process.tasks.posts]]
        name = "init_fondo_display"
        format = "protosmt2"
        file = "init_fondo_display.protosmt2"       # local file.
    [[process.tasks.posts]]
        name = "init_time_bound"
        format = "protosympy"
        file = "init_time_bound"       # local file without extension.
[[process.tasks]]
    name = "filtering"
    [[process.tasks.pres]]
        name = "filtering_pre"
        format = "protosmt2"
        file = "filtering_pre.protosmt2"       # local file.
    [[process.tasks.posts]]
        name = "filtering_post"
        format = "protosmt2"
        file = "filtering_post.protosmt2"       # local file.
    [[process.tasks.posts]]
        name = "filtering_time_bound"
        format = "protopy"
        file = "filtering_time_bound.protopy"       # local file.
    [[process.tasks.checkpoints]]
        name = "filtering_chk"
        [[process.tasks.checkpoints.properties]]
            name = "12bitsreading"
            format = "protosympy"
            file = "12bitsreading.protosympy"       # local file.
        [[process.tasks.checkpoints.properties]]
            name = "additionbound"
            format = "protopy"
            file = "additionbound.protopy"       # local file.

[[process.tasks]]
    name = "conversion"
    [[process.tasks.pres]]
        name = "conversion_pre"
        format = "protosmt2"
        file = "conversion_pre.protosmt2"       # local file.
    [[process.tasks.posts]]
        name = "conversion_post"
        format = "protosmt2"
        file = "conversion_post.protosmt2"       # local file.
    [[process.tasks.checkpoints]]

[[process.checkpoints]]
    name = "display_chk"
    [[process.checkpoints.properties]]
        name = "barpointiscorrect"
        format = "protosmt2"
        file = "barpointiscorrect.protosmt2"       # local file.
    [[process.checkpoints.properties]]
        name = "bariscorrect"
        format = "protosmt2"
        file = "bariscorrect.protosmt2"       # local file.

[[components]]
    name = "adc"
    component = "framework.components.rt_monitor_example_app.ex_adc_visual_selflogging.adc"        # python relative component name
    visual_component = "framework.components.rt_monitor_example_app.ex_adcVisual.adcVisual"
    visual = true
[[components]]
    name = "display"
    component = "framework.components.rt_monitor_example_app.ex_display.display"        # python relative component name
    visual_component = "framework.components.rt_monitor_example_app.ex_displayVisual.displayVisual"
    visual = true
